import assert from "node:assert/strict";
import test from "node:test";
import type { Goal, LocalState, Project, TaskItem } from "./types";
import type { HomeCalendarEvent } from "./home-summary";
const apiPromise = import("./home-summary");
const stamp="2026-08-10T00:00:00Z";
const state:LocalState={schemaVersion:3,morningDate:"2026-08-10",goal:"일간 목표",reason:"이유",enjoyment:"즐길 것",gratitude:["a","b","c"],parentWeeklyGoalId:"wg",tasks:[
 {id:"today",title:"오늘 할 일",done:true,doneAt:"2026-08-10",bucket:"today",scheduledAt:"2026-08-10T09:00:00",durationMinutes:30,syncCalendar:false,contextId:"personal"},
 {id:"week",title:"주간 할 일",done:false,bucket:"week",scheduledAt:"2026-08-12T09:00:00",durationMinutes:30,syncCalendar:false,contextId:"work"},
 {id:"month",title:"월간 할 일",done:false,bucket:"month",scheduledAt:"2026-08-20T09:00:00",durationMinutes:30,syncCalendar:false,contextId:"personal"}
],people:[],activities:[],notes:[],reviews:{},chapters:[],contexts:[{id:"personal",key:"PERSONAL",name:"개인",sortOrder:1,isActive:true},{id:"work",key:"WORK",name:"직장",sortOrder:2,isActive:true},{id:"church",key:"CHURCH",name:"교회",sortOrder:3,isActive:true}],calendarContextMappings:[{calendarId:"personal-cal",contextId:"personal"},{calendarId:"work-cal",contextId:"work"}],contextCalendarPreferences:[],recurringTasks:[{id:"r",title:"매일 루틴",recurrence:{type:"DAILY"},startDate:"2026-08-01",priority:"normal",showOnCalendar:false,isActive:true,createdAt:stamp,updatedAt:stamp,contextId:"personal"}],recurringTaskCompletions:[{recurringTaskId:"r",occurrenceDate:"2026-08-10",status:"done",completedAt:stamp}],plans:[{id:"wp",horizon:"WEEK",contextId:"personal",periodStart:"2026-08-10",periodEnd:"2026-08-16",direction:"주간 방향",createdAt:stamp,updatedAt:stamp},{id:"mp",horizon:"MONTH",contextId:"personal",periodStart:"2026-08-01",periodEnd:"2026-08-31",direction:"월간 방향",createdAt:stamp,updatedAt:stamp}],goals:[{id:"mg",horizon:"MONTH",contextId:"personal",periodStart:"2026-08-01",periodEnd:"2026-08-31",title:"월간 목표",status:"active",priority:"normal",createdAt:stamp,updatedAt:stamp},{id:"wg",horizon:"WEEK",parentGoalId:"mg",contextId:"personal",periodStart:"2026-08-10",periodEnd:"2026-08-16",title:"주간 목표",status:"done",priority:"high",createdAt:stamp,updatedAt:stamp}],projects:[{id:"p",name:"개인 프로젝트",goal:"",next:"",status:"active",milestones:[{id:"m",title:"",done:true,weight:1}],note:"",contextId:"personal"},{id:"w",name:"업무 프로젝트",goal:"",next:"",status:"active",milestones:[],note:"",contextId:"work"}]};
const events=[{id:"e1",title:"개인 일정",start:"2026-08-10T10:00:00",calendarId:"personal-cal"},{id:"e2",title:"업무 일정",start:"2026-08-12T10:00:00",calendarId:"work-cal"},{id:"e3",title:"다음 달",start:"2026-09-01T10:00:00",calendarId:"personal-cal"}];
test("daily summary keeps hierarchy and completion counts",async()=>{const {getDailyHomeSummary}=await apiPromise;const result=getDailyHomeSummary({state,events,date:"2026-08-10",context:"PERSONAL"});assert.equal(result.daily?.linkedWeeklyGoal?.id,"wg");assert.equal(result.todos.length,1);assert.deepEqual(result.recurringProgress,{total:1,completed:1,remaining:0});assert.equal(result.events.length,1)});
test("weekly range and context filter isolate execution data",async()=>{const {getWeeklyHomeSummary}=await apiPromise;const personal=getWeeklyHomeSummary({state,events,date:"2026-08-12",context:"PERSONAL"});assert.equal(personal.start,"2026-08-10");assert.deepEqual(personal.goals.map((goal:Goal)=>goal.id),["wg"]);assert.deepEqual(personal.projects.map((project:Project)=>project.id),["p"]);assert.deepEqual(personal.events.map((event:HomeCalendarEvent)=>event.id),["e1"]);const work=getWeeklyHomeSummary({state,events,date:"2026-08-12",context:"WORK"});assert.deepEqual(work.todos.map((todo:TaskItem)=>todo.id),["week"]);assert.deepEqual(work.events.map((event:HomeCalendarEvent)=>event.id),["e2"])});
test("monthly summary includes month data but excludes next month",async()=>{const {getMonthlyHomeSummary}=await apiPromise;const result=getMonthlyHomeSummary({state,events,date:"2026-08-10",context:"PERSONAL"});assert.equal(result.start,"2026-08-01");assert.deepEqual(result.goals.map((goal:Goal)=>goal.id),["mg"]);assert.deepEqual(result.todos.map((todo:TaskItem)=>todo.id).sort(),["month","today"]);assert.deepEqual(result.events.map((event:HomeCalendarEvent)=>event.id),["e1"])});
test("empty context produces natural empty collections",async()=>{const {getWeeklyHomeSummary}=await apiPromise;const result=getWeeklyHomeSummary({state,events:[],date:"2026-08-10",context:"CHURCH"});assert.equal(result.events.length,0);assert.equal(result.todos.length,0);assert.equal(result.recurring.length,0);assert.equal(result.goals.length,0);assert.equal(result.projects.length,0)});
