"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type View = "home"|"calendar"|"tasks"|"projects"|"people"|"activities"|"notes"|"review"|"timeline"|"dashboard"|"chapters"|"settings";
type CalendarMode = "month"|"week"|"day";
type TaskBucket = "today"|"week"|"month"|"someday";
type ActivityType = "running"|"workout"|"martial"|"reading"|"study"|"church"|"photo"|"other";
type NoteType = "idea"|"thought"|"question"|"principle"|"quote";
type Recurrence = "none"|"daily"|"weekdays"|"weekly"|"biweekly"|"monthly"|"yearly";

type EventItem = { id:string; title:string; start:string; end:string; location:string; description:string; recurrence?:string[]; reminders?:number; htmlLink?:string };
type MailItem = { id:string; from:string; subject:string; date:string; snippet:string };
type TaskItem = { id:string; title:string; done:boolean; bucket:TaskBucket; scheduledAt:string; durationMinutes:number; syncCalendar:boolean; calendarEventId?:string; projectId?:string };
type Person = { id:string; name:string; tags:string[]; lastContact:string; nextContact:string; note:string; phone?:string; email?:string };
type Milestone = { id:string; title:string; done:boolean; weight:number };
type Project = { id:string; name:string; goal:string; next:string; status:"planning"|"active"|"review"|"done"; milestones:Milestone[]; note:string };
type Activity = { id:string; date:string; type:ActivityType; title:string; duration:number; amount:number; unit:string; note:string; learned:string; applied:string; meta:Record<string,string|number> };
type Note = { id:string; date:string; type:NoteType; title:string; body:string; tags:string[] };
type Review = { date:string; goal:string; enjoyment:string; status:"done"|"not_done"|"changed"|""; reason:string; good:string; learned:string; joy:string; gratitude:string };
type Chapter = { id:string; title:string; startDate:string; endDate:string; description:string; active:boolean };
type LocalState = {
  morningDate:string; goal:string; reason:string; enjoyment:string; gratitude:string[];
  tasks:TaskItem[]; people:Person[]; projects:Project[]; activities:Activity[]; notes:Note[];
  reviews:Record<string,Review>; chapters:Chapter[];
};
type EventForm = { id?:string; title:string; start:string; end:string; location:string; description:string; recurrence:Recurrence; reminders:number };

const KEY="jeong_lifeos_v5";
const LEGACY_KEYS=["jeong_integrated_google_v33","jeong_integrated_google_v32","jeong_integrated_google_v31"];
const todayKey=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const uid=()=>crypto.randomUUID?.()??`${Date.now()}-${Math.random()}`;
const toLocalInput=(value?:string)=>{const d=value?new Date(value):new Date(); return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)};
const eventTime=(v:string)=>{const d=new Date(v); return Number.isNaN(d.getTime())||!v.includes("T")?"종일":d.toLocaleTimeString("ko-KR",{hour:"2-digit",minute:"2-digit"})};
const activityLabels:Record<ActivityType,string>={running:"러닝",workout:"근력 운동",martial:"무도",reading:"독서",study:"공부",church:"교회·교육",photo:"사진",other:"기타"};
const noteLabels:Record<NoteType,string>={idea:"아이디어",thought:"생각",question:"질문",principle:"기준",quote:"어록"};
const bucketLabels:Record<TaskBucket,string>={today:"오늘",week:"이번 주",month:"이번 달",someday:"언젠가"};
const defaultProjects:Project[]=[
 {id:"insurance",name:"우리동네 보험점검",goal:"지역에서 신뢰받는 보험 점검 채널과 고객 흐름 구축",next:"고객 또는 콘텐츠와 연결되는 행동 하나",status:"active",note:"",milestones:[{id:"i1",title:"콘텐츠 운영 체계",done:false,weight:30},{id:"i2",title:"고객 관리 체계",done:false,weight:35},{id:"i3",title:"지역 제휴 체계",done:false,weight:35}]},
 {id:"jeong",name:"JEONG",goal:"황제가 실제로 매일 사용하는 개인 운영체제 완성",next:"실사용에서 불편한 기능 하나 개선",status:"active",note:"",milestones:[{id:"j1",title:"Google 연동",done:true,weight:20},{id:"j2",title:"하루 운영",done:true,weight:20},{id:"j3",title:"프로젝트·사람",done:false,weight:20},{id:"j4",title:"활동·기록",done:false,weight:20},{id:"j5",title:"AI·Life Graph",done:false,weight:20}]},
 {id:"nextlevel",name:"넥스트레벨",goal:"자기 삶을 찾고 살아가도록 돕는 구조 설계",next:"구조 한 부분 정리",status:"planning",note:"",milestones:[]},
 {id:"running",name:"We are Run",goal:"러닝과 사유를 연결한 신뢰도 높은 채널 운영",next:"러닝 기록 또는 콘텐츠 하나",status:"active",note:"",milestones:[]},
 {id:"education",name:"교회·교육",goal:"학생이 스스로 생각하도록 돕는 교육",next:"가까운 수업 준비 확인",status:"active",note:"",milestones:[]}
];
const defaultState:LocalState={
 morningDate:"",goal:"",reason:"",enjoyment:"",gratitude:["","",""] ,tasks:[],people:[],projects:defaultProjects,activities:[],notes:[],reviews:{},chapters:[{id:"c1",title:"JEONG를 현실로 만드는 시기",startDate:todayKey(),endDate:"",description:"생각을 실제로 사용하는 시스템으로 만드는 챕터",active:true}]
};
function loadState():LocalState{
 if(typeof window==="undefined") return defaultState;
 const raw=localStorage.getItem(KEY)??LEGACY_KEYS.map(k=>localStorage.getItem(k)).find(Boolean)??null;
 if(!raw) return defaultState;
 try{
  const s=JSON.parse(raw);
  const people=(s.people??s.contacts??[]).map((p:any)=>({id:p.id??uid(),name:p.name??"",tags:p.tags??["보험"],lastContact:p.lastContact??"",nextContact:p.nextContact??p.date??"",note:p.note??p.purpose??"",phone:p.phone??"",email:p.email??""}));
  const projects=(s.projects?.length?s.projects:defaultProjects).map((p:any)=>({id:p.id??uid(),name:p.name??"프로젝트",goal:p.goal??"",next:p.next??"",status:p.status??"active",note:p.note??"",milestones:p.milestones??[]}));
  const notes=s.notes??Object.entries(s.memory??{}).filter(([,v])=>v).map(([type,body])=>({id:uid(),date:todayKey(),type:type==="principle"?"principle":"thought",title:noteLabels[(type==="principle"?"principle":"thought") as NoteType],body:String(body),tags:[]}));
  return {...defaultState,...s,people,projects,notes,activities:s.activities??[],reviews:s.reviews??{},chapters:s.chapters??defaultState.chapters,gratitude:Array.isArray(s.gratitude)?s.gratitude:["","",""]};
 }catch{return defaultState}
}
function progress(p:Project){const total=p.milestones.reduce((a,m)=>a+Math.max(0,m.weight),0); if(!total)return p.status==="done"?100:0; return Math.round(p.milestones.filter(m=>m.done).reduce((a,m)=>a+m.weight,0)/total*100)}
function monthDays(cursor:Date){const first=new Date(cursor.getFullYear(),cursor.getMonth(),1); const start=new Date(cursor.getFullYear(),cursor.getMonth(),1-first.getDay()); return Array.from({length:42},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return d})}
function rangeFor(mode:CalendarMode,cursor:Date){if(mode==="month")return {start:new Date(cursor.getFullYear(),cursor.getMonth(),1),end:new Date(cursor.getFullYear(),cursor.getMonth()+1,1)}; if(mode==="week"){const s=new Date(cursor);s.setDate(s.getDate()-s.getDay());s.setHours(0,0,0,0);const e=new Date(s);e.setDate(e.getDate()+7);return {start:s,end:e}} const s=new Date(cursor);s.setHours(0,0,0,0);const e=new Date(s);e.setDate(e.getDate()+1);return {start:s,end:e}}
function emptyReview(date:string,state:LocalState):Review{return {date,goal:date===todayKey()?state.goal:"",enjoyment:date===todayKey()?state.enjoyment:"",status:"",reason:"",good:"",learned:"",joy:"",gratitude:""}}
function eventStatus(e:EventItem){const n=Date.now(),s=new Date(e.start).getTime(),end=new Date(e.end).getTime(); if(n>=end)return "완료"; if(n>=s)return "진행 중"; return "예정"}
function recurrenceRule(r:Recurrence,start:string){const d=new Date(start);const day=["SU","MO","TU","WE","TH","FR","SA"][d.getDay()]; if(r==="daily")return "RRULE:FREQ=DAILY";if(r==="weekdays")return "RRULE:FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR";if(r==="weekly")return `RRULE:FREQ=WEEKLY;BYDAY=${day}`;if(r==="biweekly")return `RRULE:FREQ=WEEKLY;INTERVAL=2;BYDAY=${day}`;if(r==="monthly")return `RRULE:FREQ=MONTHLY;BYMONTHDAY=${d.getDate()}`;if(r==="yearly")return `RRULE:FREQ=YEARLY;BYMONTH=${d.getMonth()+1};BYMONTHDAY=${d.getDate()}`;return ""}

export function Dashboard(){
 const [local,setLocal]=useState<LocalState>(defaultState); const [hydrated,setHydrated]=useState(false); const [theme,setTheme]=useState<"light"|"dark">("light");
 const [view,setView]=useState<View>("home"); const [search,setSearch]=useState(""); const [showMorning,setShowMorning]=useState(false);
 const [events,setEvents]=useState<EventItem[]>([]); const [mails,setMails]=useState<MailItem[]>([]); const [loading,setLoading]=useState(false); const [calendarError,setCalendarError]=useState("");
 const [calendarMode,setCalendarMode]=useState<CalendarMode>("month"); const [cursor,setCursor]=useState(new Date()); const [selectedDate,setSelectedDate]=useState(new Date()); const [eventForm,setEventForm]=useState<EventForm|null>(null);
 const [taskBucket,setTaskBucket]=useState<TaskBucket>("today"); const [taskTitle,setTaskTitle]=useState(""); const [taskWhen,setTaskWhen]=useState(""); const [taskDuration,setTaskDuration]=useState(60); const [taskSync,setTaskSync]=useState(false);
 const [selectedProject,setSelectedProject]=useState<string>("jeong"); const [personName,setPersonName]=useState(""); const [personTag,setPersonTag]=useState("보험");
 const [activityType,setActivityType]=useState<ActivityType>("running"); const [activityTitle,setActivityTitle]=useState(""); const [activityDate,setActivityDate]=useState(todayKey()); const [activityDuration,setActivityDuration]=useState(60); const [activityAmount,setActivityAmount]=useState(0); const [activityNote,setActivityNote]=useState(""); const [activityLearned,setActivityLearned]=useState(""); const [activityApplied,setActivityApplied]=useState("");
 const [noteType,setNoteType]=useState<NoteType>("idea"); const [noteTitle,setNoteTitle]=useState(""); const [noteBody,setNoteBody]=useState(""); const [reviewDate,setReviewDate]=useState(todayKey());
 const [chapterTitle,setChapterTitle]=useState(""); const [chapterDescription,setChapterDescription]=useState("");

 useEffect(()=>{const s=loadState();setLocal(s);setShowMorning(s.morningDate!==todayKey());const t=(localStorage.getItem("jeong_theme") as "light"|"dark"|null)??"light";setTheme(t);document.documentElement.dataset.theme=t;setHydrated(true)},[]);
 useEffect(()=>{if(hydrated)localStorage.setItem(KEY,JSON.stringify(local))},[local,hydrated]);
 const update=<K extends keyof LocalState>(key:K,value:LocalState[K])=>setLocal(s=>({...s,[key]:value}));
 const toggleTheme=()=>{const n=theme==="light"?"dark":"light";setTheme(n);localStorage.setItem("jeong_theme",n);document.documentElement.dataset.theme=n};

 async function loadCalendar(){setLoading(true);setCalendarError("");const r=rangeFor(calendarMode,cursor);const q=new URLSearchParams({start:r.start.toISOString(),end:r.end.toISOString()});try{const [cr,mr]=await Promise.all([fetch(`/api/calendar?${q}`,{cache:"no-store"}),fetch("/api/gmail",{cache:"no-store"})]);if(cr.ok)setEvents((await cr.json()).events??[]);else setCalendarError("Google Calendar를 불러오지 못했습니다.");if(mr.ok)setMails((await mr.json()).messages??[])}finally{setLoading(false)}}
 useEffect(()=>{if(hydrated)loadCalendar()},[hydrated,calendarMode,cursor]);

 const currentReview=local.reviews[reviewDate]??emptyReview(reviewDate,local);
 const updateReview=(patch:Partial<Review>)=>setLocal(s=>({...s,reviews:{...s.reviews,[reviewDate]:{...(s.reviews[reviewDate]??emptyReview(reviewDate,s)),...patch,date:reviewDate}}}));
 const todayEvents=events.filter(e=>new Date(e.start).toDateString()===new Date().toDateString());
 const todayTasks=local.tasks.filter(t=>t.bucket==="today"&&!t.done);
 const duePeople=local.people.filter(p=>p.nextContact&&p.nextContact<=todayKey());
 const activeProjects=local.projects.filter(p=>p.status!=="done");
 const hour=new Date().getHours(); const greeting=hour<12?"좋은 아침입니다, 황제.":hour<18?"좋은 오후입니다, 황제.":"좋은 저녁입니다, 황제.";
 const briefing=[todayEvents.length?`오늘 일정 ${todayEvents.length}건`:`오늘 일정 없음`,todayTasks.length?`오늘 할 일 ${todayTasks.length}건`:`오늘 할 일 없음`,duePeople.length?`연락 확인 ${duePeople.length}건`:`연락 확인 없음`,activeProjects.length?`진행 프로젝트 ${activeProjects.length}개`:"진행 프로젝트 없음"];
 const selectedProjectData=local.projects.find(p=>p.id===selectedProject)??local.projects[0];
 const reviewDates=Object.keys(local.reviews).sort((a,b)=>b.localeCompare(a));
 const timeline=[...local.activities.map(a=>({date:a.date,kind:activityLabels[a.type],title:a.title,note:a.note})),...local.notes.map(n=>({date:n.date,kind:noteLabels[n.type],title:n.title,note:n.body})),...Object.values(local.reviews).map(r=>({date:r.date,kind:"리뷰",title:r.goal||"하루 리뷰",note:r.joy||r.good})),...local.tasks.filter(t=>t.done).map(t=>({date:t.scheduledAt?.slice(0,10)||todayKey(),kind:"완료",title:t.title,note:""}))].sort((a,b)=>b.date.localeCompare(a.date));
 const monthPrefix=todayKey().slice(0,7); const monthActivities=local.activities.filter(a=>a.date.startsWith(monthPrefix));
 const searchResults=useMemo(()=>{const q=search.trim().toLowerCase();if(!q)return[];return [
  ...local.tasks.filter(x=>x.title.toLowerCase().includes(q)).map(x=>({kind:"할 일",title:x.title,note:bucketLabels[x.bucket]})),
  ...local.projects.filter(x=>(x.name+x.goal+x.next+x.note).toLowerCase().includes(q)).map(x=>({kind:"프로젝트",title:x.name,note:x.next})),
  ...local.people.filter(x=>(x.name+x.note+x.tags.join(" ")).toLowerCase().includes(q)).map(x=>({kind:"사람",title:x.name,note:x.tags.join(" · ")})),
  ...local.activities.filter(x=>(x.title+x.note+x.learned+x.applied).toLowerCase().includes(q)).map(x=>({kind:activityLabels[x.type],title:x.title,note:x.note})),
  ...local.notes.filter(x=>(x.title+x.body+x.tags.join(" ")).toLowerCase().includes(q)).map(x=>({kind:noteLabels[x.type],title:x.title,note:x.body}))
 ]},[search,local]);

 function saveMorning(e:FormEvent){e.preventDefault();setLocal(s=>({...s,morningDate:todayKey()}));setShowMorning(false)}
 function openNewEvent(date=selectedDate){const s=new Date(date);s.setHours(9,0,0,0);const e=new Date(s);e.setHours(10,0,0,0);setEventForm({title:"",start:toLocalInput(s.toISOString()),end:toLocalInput(e.toISOString()),location:"",description:"",recurrence:"none",reminders:30})}
 function openEvent(e:EventItem){setEventForm({id:e.id,title:e.title,start:toLocalInput(e.start),end:toLocalInput(e.end),location:e.location,description:e.description,recurrence:"none",reminders:e.reminders??30})}
 async function saveEvent(e:FormEvent){e.preventDefault();if(!eventForm)return;const body={...eventForm,start:new Date(eventForm.start).toISOString(),end:new Date(eventForm.end).toISOString(),recurrence:eventForm.recurrence==="none"?[]:[recurrenceRule(eventForm.recurrence,eventForm.start)]};const r=await fetch("/api/calendar",{method:eventForm.id?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok){alert("Google Calendar 저장에 실패했습니다.");return}setEventForm(null);loadCalendar()}
 async function deleteEvent(){if(!eventForm?.id||!confirm("이 일정을 삭제할까요?"))return;await fetch(`/api/calendar?id=${encodeURIComponent(eventForm.id)}`,{method:"DELETE"});setEventForm(null);loadCalendar()}
 async function addTask(){if(!taskTitle.trim())return;const task:TaskItem={id:uid(),title:taskTitle.trim(),done:false,bucket:taskBucket,scheduledAt:taskWhen,durationMinutes:taskDuration,syncCalendar:taskSync};if(taskSync){if(!taskWhen)return alert("캘린더 저장에는 날짜와 시간이 필요합니다.");const s=new Date(taskWhen),e=new Date(s.getTime()+taskDuration*60000);const r=await fetch("/api/calendar",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:task.title,start:s.toISOString(),end:e.toISOString(),location:"",description:"JEONG 할 일",recurrence:[],reminders:30})});if(!r.ok)return alert("캘린더 저장에 실패했습니다.");task.calendarEventId=(await r.json()).event?.id;loadCalendar()}update("tasks",[...local.tasks,task]);setTaskTitle("");setTaskWhen("");setTaskSync(false)}
 function addPerson(){if(!personName.trim())return;update("people",[...local.people,{id:uid(),name:personName.trim(),tags:[personTag],lastContact:"",nextContact:"",note:""}]);setPersonName("")}
 function addActivity(){if(!activityTitle.trim())return;const unit=activityType==="running"?"km":activityType==="reading"?"page":activityType==="workout"?"세트":"";update("activities",[...local.activities,{id:uid(),date:activityDate,type:activityType,title:activityTitle,duration:activityDuration,amount:activityAmount,unit,note:activityNote,learned:activityLearned,applied:activityApplied,meta:{}}]);setActivityTitle("");setActivityNote("");setActivityLearned("");setActivityApplied("");setActivityAmount(0)}
 function addNote(){if(!noteTitle.trim()&&!noteBody.trim())return;update("notes",[...local.notes,{id:uid(),date:todayKey(),type:noteType,title:noteTitle||noteLabels[noteType],body:noteBody,tags:[]}]);setNoteTitle("");setNoteBody("")}
 function addChapter(){if(!chapterTitle.trim())return;update("chapters",[...local.chapters.map(c=>({...c,active:false})),{id:uid(),title:chapterTitle,startDate:todayKey(),endDate:"",description:chapterDescription,active:true}]);setChapterTitle("");setChapterDescription("")}

 const groups=[{label:"홈",items:[{v:"home",t:"오늘"}]},{label:"일정",items:[{v:"calendar",t:"캘린더"},{v:"tasks",t:"할 일"}]},{label:"관리",items:[{v:"projects",t:"프로젝트"},{v:"people",t:"사람"}]},{label:"기록",items:[{v:"activities",t:"활동 기록"},{v:"notes",t:"황제노트"},{v:"review",t:"리뷰"},{v:"timeline",t:"타임라인"}]},{label:"분석",items:[{v:"dashboard",t:"대시보드"},{v:"chapters",t:"챕터"}]},{label:"",items:[{v:"settings",t:"설정"}]}] as const;
 if(!hydrated)return null;
 return <div className="lifeShell">
  {showMorning&&<div className="overlay"><form className="morningCard" onSubmit={saveMorning}><div className="modalHead"><div><span>오늘 시작</span><h2>{greeting}</h2></div><button type="button" className="softBtn" onClick={()=>setShowMorning(false)}>나중에</button></div><label>오늘 목표<textarea required value={local.goal} onChange={e=>update("goal",e.target.value)}/></label><label>선택한 이유<textarea value={local.reason} onChange={e=>update("reason",e.target.value)}/></label><label>오늘 즐길 것<textarea value={local.enjoyment} onChange={e=>update("enjoyment",e.target.value)}/></label><fieldset><legend>감사 3가지</legend>{[0,1,2].map(i=><input key={i} value={local.gratitude[i]??""} onChange={e=>update("gratitude",local.gratitude.map((x,j)=>j===i?e.target.value:x))}/>)}</fieldset><button className="goldBtn">오늘 시작하기</button></form></div>}
  <aside className="premiumSidebar"><div className="brandBlock"><div className="seal">整</div><div><strong>PROJECT JEONG</strong><small>Your Private Assistant</small></div></div><div className="navScroll">{groups.map((g,gi)=><section className="navGroup" key={gi}>{g.label&&<span>{g.label}</span>}{g.items.map(i=><button key={i.v} className={view===i.v?"active":""} onClick={()=>setView(i.v as View)}>{i.t}</button>)}</section>)}</div><div className="profileChip"><div>황제</div><span>고금제일 황제 👑</span></div></aside>
  <main className="contentArea"><header className="topHeader"><div><p>{new Date().toLocaleDateString("ko-KR",{year:"numeric",month:"long",day:"numeric",weekday:"short"})}</p><h1>{view==="home"?greeting:groups.flatMap(g=>g.items).find(i=>i.v===view)?.t}</h1></div><div className="headerTools"><div className="searchBox"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="전체 검색"/>{search&&<div className="searchPopup">{searchResults.slice(0,8).map((r,i)=><article key={i}><span>{r.kind}</span><strong>{r.title}</strong><small>{r.note}</small></article>)}{!searchResults.length&&<p>검색 결과가 없습니다.</p>}</div>}</div><button className="iconBtn" onClick={toggleTheme}>{theme==="light"?"☾":"☀"}</button><button className="iconBtn" onClick={()=>setShowMorning(true)}>☰</button></div></header>

  {view==="home"&&<div className="homeGrid"><section className="mainColumn"><article className="premiumCard morningPanel"><div className="cardTitle"><h2>🌅 오늘 아침 기록</h2><button className="goldBtn" onClick={()=>setLocal(s=>({...s,morningDate:todayKey()}))}>✓ 저장하기</button></div><div className="morningGrid"><label>🎯 1. 오늘 목표<textarea value={local.goal} onChange={e=>update("goal",e.target.value)} placeholder="오늘의 가장 중요한 목표는?"/></label><label>⭐ 2. 선택한 이유<textarea value={local.reason} onChange={e=>update("reason",e.target.value)} placeholder="왜 이 목표가 오늘 가장 중요한가?"/></label><label>💗 3. 오늘 즐길 것<textarea value={local.enjoyment} onChange={e=>update("enjoyment",e.target.value)} placeholder="오늘 무엇을 누리고 즐길 것인가?"/></label><label>🌿 4. 감사 3가지<div className="gratitudeList">{[0,1,2].map(i=><div key={i}><b>{i+1}.</b><input value={local.gratitude[i]??""} onChange={e=>update("gratitude",local.gratitude.map((x,j)=>j===i?e.target.value:x))}/></div>)}</div></label></div></article><article className="premiumCard reportPanel"><div className="cardTitle"><h2>🧠 오늘 보고</h2></div><div className="briefBubble"><strong>현재 상태</strong>{briefing.map(x=><p key={x}>• {x}</p>)}<p className="recommend">추천 · {todayTasks[0]?.title??todayEvents[0]?.title??"오늘 목표를 시작할 첫 행동 하나를 정하세요."}</p></div></article></section><aside className="rightRail"><article className="premiumCard"><div className="cardTitle"><h2>▣ 오늘 일정</h2><button onClick={()=>setView("calendar")}>전체 보기</button></div><div className="compactList">{todayEvents.slice(0,5).map(e=>{const s=eventStatus(e);return <article key={e.id} onClick={()=>openEvent(e)}><time>{eventTime(e.start)}</time><div><strong>{e.title}</strong><small>{e.location||"장소 미입력"}</small></div><span className={s==="완료"?"done":s==="진행 중"?"doing":"planned"}>{s}</span></article>})}{!todayEvents.length&&<p>오늘 일정이 없습니다.</p>}</div></article><article className="premiumCard"><div className="cardTitle"><h2>⚠ 확인이 필요한 것</h2><button onClick={()=>setView("tasks")}>전체 보기</button></div><div className="attentionList">{todayTasks.slice(0,3).map(t=><article key={t.id}><b>□</b><div><strong>{t.title}</strong><small>{t.scheduledAt?new Date(t.scheduledAt).toLocaleString("ko-KR"):"오늘 할 일"}</small></div></article>)}{duePeople.slice(0,2).map(p=><article key={p.id}><b>●</b><div><strong>{p.name} 연락</strong><small>{p.note||p.tags.join(" · ")}</small></div></article>)}{!todayTasks.length&&!duePeople.length&&<p>확인할 항목이 없습니다.</p>}</div></article><article className="premiumCard"><div className="cardTitle"><h2>📁 진행 중인 프로젝트</h2><button onClick={()=>setView("projects")}>전체 보기</button></div>{activeProjects.slice(0,3).map(p=><div className="miniProject" key={p.id}><div><strong>{p.name}</strong><span>{progress(p)}%</span></div><i><b style={{width:`${progress(p)}%`}}/></i></div>)}</article></aside></div>}

  {view==="calendar"&&<section className="premiumCard calendarPage"><div className="calendarToolbar"><div><button onClick={()=>setCursor(new Date())}>오늘</button><button onClick={()=>{const d=new Date(cursor);calendarMode==="month"?d.setMonth(d.getMonth()-1):calendarMode==="week"?d.setDate(d.getDate()-7):d.setDate(d.getDate()-1);setCursor(d)}}>‹</button><button onClick={()=>{const d=new Date(cursor);calendarMode==="month"?d.setMonth(d.getMonth()+1):calendarMode==="week"?d.setDate(d.getDate()+7):d.setDate(d.getDate()+1);setCursor(d)}}>›</button><strong>{cursor.toLocaleDateString("ko-KR",{year:"numeric",month:"long",day:calendarMode==="day"?"numeric":undefined})}</strong></div><div><button className={calendarMode==="month"?"active":""} onClick={()=>setCalendarMode("month")}>월</button><button className={calendarMode==="week"?"active":""} onClick={()=>setCalendarMode("week")}>주</button><button className={calendarMode==="day"?"active":""} onClick={()=>setCalendarMode("day")}>일</button><button className="goldBtn" onClick={()=>openNewEvent()}>일정 추가</button></div></div>{calendarError&&<p>{calendarError}</p>}{calendarMode==="month"&&<div className="monthCalendar"><div className="weekHeader">{["일","월","화","수","목","금","토"].map(x=><span key={x}>{x}</span>)}</div><div className="monthGrid">{monthDays(cursor).map(d=>{const de=events.filter(e=>new Date(e.start).toDateString()===d.toDateString());return <button key={d.toISOString()} className={`${d.getMonth()!==cursor.getMonth()?"outside":""} ${d.toDateString()===selectedDate.toDateString()?"selected":""}`} onClick={()=>setSelectedDate(d)}><b>{d.getDate()}</b>{de.slice(0,2).map(e=><span key={e.id} title={`${eventTime(e.start)} ${e.title}`} onClick={ev=>{ev.stopPropagation();openEvent(e)}}>{eventTime(e.start)} {e.title}</span>)}{de.length>2&&<small>+{de.length-2}개</small>}</button>})}</div></div>}{calendarMode!=="month"&&<div className="agendaView">{events.sort((a,b)=>new Date(a.start).getTime()-new Date(b.start).getTime()).map(e=><article key={e.id} onClick={()=>openEvent(e)}><time>{new Date(e.start).toLocaleDateString("ko-KR",{month:"short",day:"numeric",weekday:"short"})}<br/>{eventTime(e.start)}</time><div><strong>{e.title}</strong><small>{e.location||"장소 미입력"}</small></div><span>{eventStatus(e)}</span></article>)}</div>}</section>}

  {view==="tasks"&&<><section className="premiumCard taskComposer"><input value={taskTitle} onChange={e=>setTaskTitle(e.target.value)} placeholder="할 일을 입력하세요"/><select value={taskBucket} onChange={e=>setTaskBucket(e.target.value as TaskBucket)}>{Object.entries(bucketLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><input type="datetime-local" value={taskWhen} onChange={e=>setTaskWhen(e.target.value)}/><input type="number" min="15" step="15" value={taskDuration} onChange={e=>setTaskDuration(Number(e.target.value))}/><label><input type="checkbox" checked={taskSync} onChange={e=>setTaskSync(e.target.checked)}/> 캘린더에도 저장</label><button className="goldBtn" onClick={addTask}>추가</button></section><section className="premiumCard"><div className="taskTabs">{(Object.keys(bucketLabels) as TaskBucket[]).map(b=><button className={taskBucket===b?"active":""} onClick={()=>setTaskBucket(b)} key={b}>{bucketLabels[b]}</button>)}</div><div className="rows">{local.tasks.filter(t=>t.bucket===taskBucket).map(t=><article key={t.id}><input type="checkbox" checked={t.done} onChange={()=>update("tasks",local.tasks.map(x=>x.id===t.id?{...x,done:!x.done}:x))}/><div className={t.done?"lineDone":""}><strong>{t.title}</strong><small>{t.scheduledAt?new Date(t.scheduledAt).toLocaleString("ko-KR"):"날짜 없음"}{t.calendarEventId?" · Google Calendar":""}</small></div><button onClick={()=>update("tasks",local.tasks.filter(x=>x.id!==t.id))}>삭제</button></article>)}</div></section></>}

  {view==="projects"&&<div className="projectWorkspace"><aside className="premiumCard projectList"><div className="cardTitle"><h2>프로젝트</h2><button onClick={()=>{const name=prompt("프로젝트 이름");if(name)update("projects",[...local.projects,{id:uid(),name,goal:"",next:"",status:"planning",milestones:[],note:""}])}}>＋</button></div>{local.projects.map(p=><button className={selectedProject===p.id?"active":""} onClick={()=>setSelectedProject(p.id)} key={p.id}><div><strong>{p.name}</strong><small>{p.status}</small></div><span>{progress(p)}%</span></button>)}</aside>{selectedProjectData&&<section className="premiumCard projectDetail"><div className="projectHero"><div><span>{selectedProjectData.status}</span><h2>{selectedProjectData.name}</h2><p>{selectedProjectData.goal||"프로젝트 목표를 입력하세요."}</p></div><b>{progress(selectedProjectData)}%</b></div><div className="projectFields"><label>목표<textarea value={selectedProjectData.goal} onChange={e=>update("projects",local.projects.map(p=>p.id===selectedProjectData.id?{...p,goal:e.target.value}:p))}/></label><label>다음 행동<textarea value={selectedProjectData.next} onChange={e=>update("projects",local.projects.map(p=>p.id===selectedProjectData.id?{...p,next:e.target.value}:p))}/></label><label>상태<select value={selectedProjectData.status} onChange={e=>update("projects",local.projects.map(p=>p.id===selectedProjectData.id?{...p,status:e.target.value as Project["status"]}:p))}><option value="planning">기획</option><option value="active">진행 중</option><option value="review">검토</option><option value="done">완료</option></select></label></div><div className="milestoneHead"><div><h3>중간 목표</h3><small>프로젝트를 완성하기 위해 거쳐야 하는 큰 단계입니다.</small></div><button onClick={()=>{const title=prompt("중간 목표 이름");if(!title)return;const w=Number(prompt("진행률 비중","25"))||25;update("projects",local.projects.map(p=>p.id===selectedProjectData.id?{...p,milestones:[...p.milestones,{id:uid(),title,done:false,weight:w}]}:p))}}>중간 목표 추가</button></div><div className="milestoneCards">{selectedProjectData.milestones.map(m=><label key={m.id}><input type="checkbox" checked={m.done} onChange={()=>update("projects",local.projects.map(p=>p.id===selectedProjectData.id?{...p,milestones:p.milestones.map(x=>x.id===m.id?{...x,done:!x.done}:x)}:p))}/><strong>{m.title}</strong><span>비중 {m.weight}%</span></label>)}</div><label className="projectNote">프로젝트 메모<textarea value={selectedProjectData.note} onChange={e=>update("projects",local.projects.map(p=>p.id===selectedProjectData.id?{...p,note:e.target.value}:p))}/></label></section>}</div>}

  {view==="people"&&<><section className="premiumCard peopleComposer"><input value={personName} onChange={e=>setPersonName(e.target.value)} placeholder="이름"/><input value={personTag} onChange={e=>setPersonTag(e.target.value)} placeholder="태그"/><button className="goldBtn" onClick={addPerson}>사람 추가</button></section><section className="peopleGrid">{local.people.map(p=><article className="premiumCard" key={p.id}><div className="personHead"><div className="avatar">{p.name.slice(0,1)}</div><div><h3>{p.name}</h3><span>{p.tags.join(" · ")}</span></div></div><label>최근 연락<input type="date" value={p.lastContact} onChange={e=>update("people",local.people.map(x=>x.id===p.id?{...x,lastContact:e.target.value}:x))}/></label><label>다음 연락<input type="date" value={p.nextContact} onChange={e=>update("people",local.people.map(x=>x.id===p.id?{...x,nextContact:e.target.value}:x))}/></label><label>메모<textarea value={p.note} onChange={e=>update("people",local.people.map(x=>x.id===p.id?{...x,note:e.target.value}:x))}/></label></article>)}</section></>}

  {view==="activities"&&<><section className="premiumCard activityComposer">
<label><span>활동 종류</span><select value={activityType} onChange={e=>setActivityType(e.target.value as ActivityType)}>{Object.entries(activityLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
<label><span>날짜</span><input type="date" value={activityDate} onChange={e=>setActivityDate(e.target.value)}/></label>
<label className="activityTitleField"><span>{activityType==="reading"?"책 이름":activityType==="running"?"훈련 이름":"활동 이름"}</span><input value={activityTitle} onChange={e=>setActivityTitle(e.target.value)} placeholder={activityType==="other"?"원하는 활동 이름을 직접 입력":activityType==="reading"?"예: 설득의 심리학":activityType==="running"?"예: 10km 조깅":"예: 하체 운동"}/></label>
<label><span>활동 시간</span><div className="unitInput"><input type="number" min="0" value={activityDuration} onChange={e=>setActivityDuration(Number(e.target.value))}/><b>분</b></div></label>
<label><span>{activityType==="running"?"거리":activityType==="reading"?"읽은 분량":activityType==="workout"?"운동량":"수치(선택)"}</span><div className="unitInput"><input type="number" min="0" step="0.1" value={activityAmount} onChange={e=>setActivityAmount(Number(e.target.value))}/><b>{activityType==="running"?"km":activityType==="reading"?"쪽":activityType==="workout"?"세트":activityType==="study"?"회":""}</b></div></label>
<label className="wideField"><span>기록과 느낌</span><textarea value={activityNote} onChange={e=>setActivityNote(e.target.value)} placeholder="몸 상태, 내용, 느낀 점"/></label>
<label className="wideField"><span>배운 것</span><textarea value={activityLearned} onChange={e=>setActivityLearned(e.target.value)} placeholder="새롭게 알게 된 것"/></label>
<label className="wideField"><span>적용할 것</span><textarea value={activityApplied} onChange={e=>setActivityApplied(e.target.value)} placeholder="다음에 실제로 적용할 것"/></label>
<button className="goldBtn activitySaveBtn" onClick={addActivity}>기록 저장</button>
</section><section className="activityCards">{[...local.activities].sort((a,b)=>b.date.localeCompare(a.date)).map(a=><article className="premiumCard" key={a.id}><div className="activityHead"><span>{activityLabels[a.type]}</span><time>{a.date}</time></div><h3>{a.title}</h3><p><b>{a.duration}분</b>{a.amount?` · ${a.amount}${a.unit==="page"?"쪽":a.unit}`:""}</p>{a.note&&<small>{a.note}</small>}{a.learned&&<small>배운 것 · {a.learned}</small>}{a.applied&&<small>적용 · {a.applied}</small>}</article>)}</section></>}

  {view==="notes"&&<><section className="premiumCard noteComposer"><select value={noteType} onChange={e=>setNoteType(e.target.value as NoteType)}>{Object.entries(noteLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><input value={noteTitle} onChange={e=>setNoteTitle(e.target.value)} placeholder="제목"/><textarea value={noteBody} onChange={e=>setNoteBody(e.target.value)} placeholder="기록할 내용을 적으세요"/><button className="goldBtn" onClick={addNote}>저장</button></section><section className="noteGrid">{[...local.notes].reverse().map(n=><article className="premiumCard" key={n.id}><span>{noteLabels[n.type]} · {n.date}</span><h3>{n.title}</h3><p>{n.body}</p></article>)}</section></>}

  {view==="review"&&<div className="reviewWorkspace"><aside className="premiumCard reviewHistory"><input type="date" value={reviewDate} onChange={e=>setReviewDate(e.target.value)}/>{reviewDates.map(d=><button className={d===reviewDate?"active":""} onClick={()=>setReviewDate(d)} key={d}>{new Date(`${d}T00:00`).toLocaleDateString("ko-KR",{month:"short",day:"numeric",weekday:"short"})}</button>)}</aside><section className="premiumCard reviewForm"><div className="reviewSummary"><label>그날 목표<input value={currentReview.goal} onChange={e=>updateReview({goal:e.target.value})}/></label><label>그날 즐길 것<input value={currentReview.enjoyment} onChange={e=>updateReview({enjoyment:e.target.value})}/></label></div><div className="reviewSummary"><label>목표 결과<select value={currentReview.status} onChange={e=>updateReview({status:e.target.value as Review["status"]})}><option value="">선택</option><option value="done">완료</option><option value="not_done">미완료</option><option value="changed">우선순위 변경</option></select></label><label>이유<input value={currentReview.reason} onChange={e=>updateReview({reason:e.target.value})}/></label></div><div className="reviewGrid"><label>잘한 점<textarea value={currentReview.good} onChange={e=>updateReview({good:e.target.value})}/></label><label>배운 점<textarea value={currentReview.learned} onChange={e=>updateReview({learned:e.target.value})}/></label><label>즐거웠던 순간<textarea value={currentReview.joy} onChange={e=>updateReview({joy:e.target.value})}/></label><label>감사 3가지<textarea value={currentReview.gratitude} onChange={e=>updateReview({gratitude:e.target.value})}/></label></div></section></div>}

  {view==="timeline"&&<section className="premiumCard timelineList">{timeline.map((x,i)=><article key={`${x.date}-${i}`}><time>{x.date}</time><i/><div><span>{x.kind}</span><h3>{x.title}</h3>{x.note&&<p>{x.note}</p>}</div></article>)}</section>}

  {view==="dashboard"&&<><section className="statGrid"><article className="premiumCard"><strong>{monthActivities.length}</strong><span>이번 달 활동 기록</span></article><article className="premiumCard"><strong>{local.tasks.filter(t=>t.done).length}</strong><span>완료한 할 일</span></article><article className="premiumCard"><strong>{Object.values(local.reviews).filter(r=>r.status==="done").length}</strong><span>완료한 하루 목표</span></article><article className="premiumCard"><strong>{local.notes.length}</strong><span>황제노트</span></article></section>
<section className="premiumCard dashboardSection"><div className="cardTitle"><div><h2>이번 달 활동</h2><small>세부 기록은 활동 기록에서 추가·수정합니다.</small></div><button onClick={()=>setView("activities")}>활동 기록 열기</button></div>
<div className="activityStats grouped">
{[
 {key:"exercise",label:"운동",types:["running","workout","martial"] as ActivityType[]},
 {key:"reading",label:"독서",types:["reading"] as ActivityType[]},
 {key:"study",label:"공부",types:["study"] as ActivityType[]},
 {key:"life",label:"생활·기타",types:["church","photo","other"] as ActivityType[]}
].map(group=>{const list=monthActivities.filter(a=>group.types.includes(a.type));return <article key={group.key} onClick={()=>setView("activities")}><strong>{group.label}</strong><b>{list.length}회</b><small>{Math.round(list.reduce((s,a)=>s+a.duration,0)/6)/10}시간</small></article>})}
</div></section>
<section className="premiumCard dashboardSection"><div className="cardTitle"><div><h2>프로젝트 진행률</h2><small>진행률은 프로젝트의 중간 목표 완료 상태로 계산됩니다.</small></div><button onClick={()=>setView("projects")}>프로젝트 관리</button></div>{local.projects.map(p=><div className="miniProject clickableProject" key={p.id} onClick={()=>{setSelectedProject(p.id);setView("projects")}}><div><strong>{p.name}</strong><span>{progress(p)}%</span></div><i><b style={{width:`${progress(p)}%`}}/></i></div>)}</section></>}

  {view==="chapters"&&<><section className="premiumCard chapterComposer"><label><span>새 시기 이름</span><input value={chapterTitle} onChange={e=>setChapterTitle(e.target.value)} placeholder="예: JEONG를 완성하는 시기"/></label><label><span>이 시기의 의미</span><input value={chapterDescription} onChange={e=>setChapterDescription(e.target.value)} placeholder="무엇을 만들고 살아갈 시기인가"/></label><button className="goldBtn" onClick={addChapter}>새 시기 시작</button></section><section className="chapterGrid">{[...local.chapters].reverse().map(c=><article className={`premiumCard ${c.active?"active":""}`} key={c.id}><div className="chapterContent"><span>{c.active?"현재 시기":"지난 시기"}</span><h3>{c.title}</h3><p>{c.description}</p><small>{c.startDate}{c.endDate?` — ${c.endDate}`:" — 진행 중"}</small></div>{c.active&&<button className="chapterEndBtn" onClick={()=>update("chapters",local.chapters.map(x=>x.id===c.id?{...x,active:false,endDate:todayKey()}:x))}>현재 시기 종료</button>}</article>)}</section></>}

  {view==="settings"&&<section className="premiumCard settingsPanel"><h2>설정</h2><div><span>테마</span><button onClick={toggleTheme}>{theme==="light"?"다크 모드":"라이트 모드"}</button></div><div><span>Google 데이터</span><button onClick={loadCalendar}>{loading?"불러오는 중":"새로고침"}</button></div><div><span>로컬 데이터 백업</span><button onClick={()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(local,null,2)],{type:"application/json"}));a.download=`JEONG-${todayKey()}.json`;a.click()}}>내보내기</button></div></section>}
  </main>
  {eventForm&&<div className="overlay"><form className="eventModal" onSubmit={saveEvent}><div className="modalHead"><h2>{eventForm.id?"일정 수정":"일정 추가"}</h2><button type="button" onClick={()=>setEventForm(null)}>닫기</button></div><label>제목<input required value={eventForm.title} onChange={e=>setEventForm({...eventForm,title:e.target.value})}/></label><div className="twoFields"><label>시작<input type="datetime-local" value={eventForm.start} onChange={e=>setEventForm({...eventForm,start:e.target.value})}/></label><label>종료<input type="datetime-local" value={eventForm.end} onChange={e=>setEventForm({...eventForm,end:e.target.value})}/></label></div><div className="twoFields"><label>반복<select value={eventForm.recurrence} onChange={e=>setEventForm({...eventForm,recurrence:e.target.value as Recurrence})}><option value="none">반복 안 함</option><option value="daily">매일</option><option value="weekdays">평일</option><option value="weekly">매주</option><option value="biweekly">격주</option><option value="monthly">매월</option><option value="yearly">매년</option></select></label><label>알림<select value={eventForm.reminders} onChange={e=>setEventForm({...eventForm,reminders:Number(e.target.value)})}><option value="10">10분 전</option><option value="30">30분 전</option><option value="60">1시간 전</option><option value="1440">하루 전</option></select></label></div><label>장소<input value={eventForm.location} onChange={e=>setEventForm({...eventForm,location:e.target.value})}/></label><label>메모<textarea value={eventForm.description} onChange={e=>setEventForm({...eventForm,description:e.target.value})}/></label><div className="modalActions">{eventForm.id&&<button type="button" className="dangerBtn" onClick={deleteEvent}>삭제</button>}<button className="goldBtn">Google Calendar에 저장</button></div></form></div>}
 </div>
}
