import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/auth";
const BASE="https://www.googleapis.com/calendar/v3/calendars/primary/events";
async function token(){return (await auth())?.accessToken}
function map(item:any){return {id:item.id,title:item.summary??"제목 없는 일정",start:item.start?.dateTime??item.start?.date,end:item.end?.dateTime??item.end?.date,location:item.location??"",description:item.description??"",recurrence:item.recurrence??[],reminders:item.reminders?.overrides?.[0]?.minutes??30,htmlLink:item.htmlLink??""}}
function payload(body:any){return {summary:body.title,location:body.location||undefined,description:body.description||undefined,start:{dateTime:body.start,timeZone:"Asia/Seoul"},end:{dateTime:body.end,timeZone:"Asia/Seoul"},recurrence:Array.isArray(body.recurrence)&&body.recurrence.length?body.recurrence:undefined,reminders:{useDefault:false,overrides:[{method:"popup",minutes:Number(body.reminders??30)}]}}}
export async function GET(req:NextRequest){const access=await token();if(!access)return NextResponse.json({error:"login"},{status:401});const q=req.nextUrl.searchParams;const params=new URLSearchParams({timeMin:q.get("start")??new Date().toISOString(),timeMax:q.get("end")??new Date(Date.now()+31*86400000).toISOString(),singleEvents:"true",orderBy:"startTime",maxResults:"2500"});const r=await fetch(`${BASE}?${params}`,{headers:{Authorization:`Bearer ${access}`},cache:"no-store"});if(!r.ok)return NextResponse.json({error:"calendar",detail:await r.text()},{status:r.status});return NextResponse.json({events:((await r.json()).items??[]).map(map)})}
export async function POST(req:NextRequest){const access=await token();if(!access)return NextResponse.json({error:"login"},{status:401});const r=await fetch(BASE,{method:"POST",headers:{Authorization:`Bearer ${access}`,"Content-Type":"application/json"},body:JSON.stringify(payload(await req.json()))});if(!r.ok)return NextResponse.json({error:"create",detail:await r.text()},{status:r.status});return NextResponse.json({event:map(await r.json())})}
export async function PATCH(req:NextRequest){const access=await token();if(!access)return NextResponse.json({error:"login"},{status:401});const body=await req.json();const r=await fetch(`${BASE}/${encodeURIComponent(body.id)}`,{method:"PATCH",headers:{Authorization:`Bearer ${access}`,"Content-Type":"application/json"},body:JSON.stringify(payload(body))});if(!r.ok)return NextResponse.json({error:"update",detail:await r.text()},{status:r.status});return NextResponse.json({event:map(await r.json())})}
export async function DELETE(req:NextRequest){const access=await token();if(!access)return NextResponse.json({error:"login"},{status:401});const id=req.nextUrl.searchParams.get("id");if(!id)return NextResponse.json({error:"id"},{status:400});const r=await fetch(`${BASE}/${encodeURIComponent(id)}`,{method:"DELETE",headers:{Authorization:`Bearer ${access}`}});if(!r.ok&&r.status!==204)return NextResponse.json({error:"delete",detail:await r.text()},{status:r.status});return NextResponse.json({deleted:true})}
